// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Ereport message definitions shared between multiple tasks.

#![no_std]

pub mod cpu;
pub mod pwr;

pub use microcbor;

/// Generate client code for reporting a specified set of ereport types to
/// `packrat`.
///
/// Using this macro can make reporting ereports from a task more convenient
/// and reduces the risk of programmer errors, by eliminating boilerplate and,
/// most importantly, ensuring that *only* ereports whose encoded CBOR sizes
/// are known at compile-time to fit in the encoding buffer can be encoded
/// using the generated reporting code.
///
/// Invocations of this macro provide a list of Rust types which must implement
/// [`microcbor::StaticCborLen`] and [`microcbor::Encode`]. The macro then
/// generates the following:
///
/// - An "ereporter" `struct` which consists of a client for the
///   [`packrat`](task_packrat_api) API, along with a statically-allocated
///   buffer which is guaranteed to be large enough to fit the CBOR-encoded
///   representation of the largest of the provided ereport types.
/// - A trait, which is implemented only by the provided ereport types,
///   representing ereports that may be reported using the generated reporter
///   `struct`.
/// - A `deliver_ereport` method on the generated ereporter `struct`, which
///   encodes an ereport and delivers it to `packrat`. This method will accept
///   only an ereport which implements the generated ereport trait.
/// - A module containing supporting code for the generated implementation.
///   This includes a [`ringbuf`] and [`counters`] that record which ereport
///   classes were reported, and whether they were reported successfully.
///
/// # Usage
///
/// As this is a declarative macro, the names of the generated reporter struct
/// type, ereport trait, and ringbuf entry variants must be provided by the
/// user. This ensures that no publicly-visible identifiers generated by the
/// macro will collide with existing types in the calling scope.
///
/// Henceforth in this documentation, we shall refer to these identifiers using
/// the names of the metavariables which match them in the macro definition.
/// The following identifiers are provided when invoking the macro:
///
/// - `$Ereporter`: the identifier used for the generated reporter `struct`,
/// - `$Trait`: the name of the generated trait which is implemented by the
///   provided ereport types,
/// - For each ereport type in the list of ereport types, a `$ClassName`, which
///   is used as the name of the ringbuf entry `enum` variant that indicates
///   an attempt to report an ereport of that class.
///
/// The macro is invoked as follows:
///
/// ```rust
/// # mod some_module_with_ereport_message_types {
/// # // for illustrative purposes
/// #   pub(super) type EreportOne = usize;
/// #   pub(super) type EreportTwo =  usize;
/// # }
/// ereports::declare_ereporter! {
///     // Here, `MyEreporter` will be the name of the generated struct type,
///     // while `MyEreport` will be the name of the generated trait type.
///     pub struct MyEreporter<MyEreport> {
///         // A list of types which will be used as ereport messages with
///         // the generated reporter.
///         //
///         // Here, the `MyEreport` trait will be implemented for
///         // `some_module_with_ereport_message_types::EreportOne` and
///         // `some_module_with_ereport_message_types::EreportTwo`.
///         //
///         // The identifiers `One` and `Two` are used as the names of the
///         // ringbuf enum variants that record when these ereport types are reported.
///         One(some_module_with_ereport_message_types::EreportOne),
///         Two(some_module_with_ereport_message_types::EreportTwo),
///     }
/// }
/// ```
///
/// # Generated API
///
/// The generated `$Ereporter` type implements the following API functions:
///
/// - `fn claim_static_resources(packrat:` [`task_packrat_api::Packrat`]`) -> Self`:
///   Initializes the `$Ereporter` type, returning it.
///
///   This attempts to claim the statically-allocated encoding buffer. If the
///   buffer has already been claimed by a prior call to
///   `claim_static_resources`, this function panics.
/// - `fn deliver_ereport(&mut self, &impl $Trait) -> `[`Result`]`<`[`task_packrat_api::Ena`]`, `[`EreportDeliveryError`]`>`:
///   Attempts to deliver an ereport to `packrat`, returning the
///   [`Ena`](task_packrat_api::Ena) assigned to it if it was delivered
///   successfully, or an [`EreportDeliveryError`] if it could not be delivered.
///
///   The outcome of delivering the ereport is recorded in the generated
///   ringbuffer.
///
/// These functions inherit the visibility with which the `$Ereporter` struct is
/// declared in the macro invocation, as does the generated trait. For example,
/// if the struct is declared as `pub(crate) struct MyEreporter<MyTrait>`, then
/// the functions on `MyEreporter` and the definition of `MyTrait` are also
/// generated with `pub(crate)` visibility.
#[cfg(feature = "ereporter-macro")]
#[macro_export]
macro_rules! declare_ereporter {
    ($v:vis struct $Ereporter:ident<$Trait:ident> {
        $($ClassName:ident($EreportTy:ty $(,)?)),+ $(,)?
    }) => {
        $v struct $Ereporter {
            packrat: task_packrat_api::Packrat,
            buf: &'static mut [u8; Self::BUF_LEN],
        }

        $crate::__macro_support::paste! {
            impl $Ereporter {
                const BUF_LEN: usize = $crate::microcbor::max_cbor_len_for![
                    $($EreportTy),+
                ];

                $v fn claim_static_resources(packrat: task_packrat_api::Packrat) -> Self {
                    use $crate::__macro_support::ClaimOnceCell;
                    static EREPORT_BUF: ClaimOnceCell<[u8; $Ereporter::BUF_LEN]> =
                        ClaimOnceCell::new([0; $Ereporter::BUF_LEN]);
                    Self {
                        packrat,
                        buf: EREPORT_BUF.claim()
                    }
                }

                $v fn deliver_ereport(&mut self, ereport: &impl $Trait)
                    -> Result<task_packrat_api::Ena, $crate::EreportDeliveryError>
                {
                    [< $Ereporter:snake >]::deliver_ereport(self, ereport)
                }
            }

            $v use [< $Ereporter:snake >]::$Trait;
            $v mod [< $Ereporter:snake >] {
                use super::*;

                pub(super) trait $Trait: $crate::microcbor::StaticCborLen + sealed::Sealed {
                    fn class(&self) -> EreportClass;
                }

                $(
                    impl sealed::Sealed for $EreportTy {}
                    impl $Trait for $EreportTy {
                        fn class(&self) -> EreportClass {
                            EreportClass::$ClassName
                        }
                    }
                )+

                $crate::__macro_support::ringbuf::counted_ringbuf!(
                    __EREPORT_RINGBUF,
                    EreportTrace,
                    8,
                    EreportTrace::None
                );

                #[derive($crate::__macro_support::counters::Count, Eq, PartialEq, Copy, Clone)]
                pub(super) enum EreportClass {
                    $(
                        $ClassName
                    ),+
                }

                #[derive($crate::__macro_support::counters::Count, Eq, PartialEq, Copy, Clone)]
                enum EreportTrace {
                    #[count(skip)]
                    None,
                    EreportSent {#[count(children)] class: EreportClass, len: usize },
                    EreportLost {
                        #[count(children)] class: EreportClass,
                        len: usize,
                        err:  task_packrat_api::EreportWriteError
                    },
                    EreportTooBig { #[count(children)] class: EreportClass },
                }

                pub(super) fn deliver_ereport(this: &mut $Ereporter, ereport: &impl $Trait)
                    -> Result<task_packrat_api::Ena, $crate::EreportDeliveryError>
                {
                    use $crate::__macro_support::ringbuf::ringbuf_entry;
                    let class = ereport.class();
                    let eresult = this
                        .packrat
                        .deliver_microcbor_ereport(&ereport, &mut this.buf[..]);
                    match eresult {
                        Ok((len, ena)) => {
                            ringbuf_entry!(
                                __EREPORT_RINGBUF,
                                EreportTrace::EreportSent{ len, class }
                            );
                            Ok(ena)
                        }
                        Err(task_packrat_api::EreportEncodeError::Packrat { len, err }) => {
                            ringbuf_entry!(
                                __EREPORT_RINGBUF,
                                EreportTrace::EreportLost { len, class, err }
                            );
                            match err {
                                task_packrat_api::EreportWriteError::Lost => {
                                    Err($crate::EreportDeliveryError::BufferFull)
                                }
                            }
                        }
                        Err(task_packrat_api::EreportEncodeError::Encoder(_)) => {
                            ringbuf_entry!(
                                __EREPORT_RINGBUF,
                                EreportTrace::EreportTooBig { class }
                            );
                            Err($crate::EreportDeliveryError::EncoderFailed)
                        }
                    }

                }

                mod sealed {
                    pub trait Sealed {}
                }
            }

        }
    };
}

/// Lightweight error returned from the generated `deliver_ereport` method
/// generated by the [`declare_ereporter!`] macro.
///
/// This error lets the caller know whether they could retry (because the buffer
/// was out of space) or whether that's a lost cause (because encoding the
/// ereport failed).  It elides the details of each failure mode, which are
/// preserved in the ringbuf and are not as relevant to the caller.
#[cfg(feature = "ereporter-macro")]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum EreportDeliveryError {
    /// The encoded ereport was dropped by `packrat` because its ereport
    /// aggregation buffer was at capacity.
    ///
    /// This is a transient condition, and the same ereport may be able to be
    /// reported successfully in the future.
    BufferFull,
    /// Encoding the ereport failed.
    EncoderFailed,
}

/// Stuff from other crates which are publicly re-exported for use by the
/// `declare_ereporter!` macro.
#[cfg(feature = "ereporter-macro")]
#[doc(hidden)]
pub mod __macro_support {
    pub use counters;
    pub use paste::paste;
    pub use ringbuf;
    pub use static_cell::ClaimOnceCell;
}
