# Configuration fragment for -dev images

[tasks.jefe.config.allowed-callers]
request_reset = ["udprpc"]

[tasks.hiffy]
features = ["net", "vlan"]
notifications = ["socket"]
task-slots = ["net"]

[config.net.sockets.hiffy]
kind = "udp"
owner = {name = "hiffy", notification = "socket"}
port = 11115
tx = { packets = 3, bytes = 32 }
rx = { packets = 1, bytes = 4096 }

[tasks.udprpc]
name = "task-udprpc"
priority = 5
max-sizes = {flash = 32768, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]
notifications = ["socket"]

[config.net.sockets.rpc]
kind = "udp"
owner = {name = "udprpc", notification = "socket"}
port = 998
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

# This writes test data to the FRAM, so if we start actually using the FRAM then
# we should remove this task to avoid clobbering the real data.
[tasks.framulator]
name = "task-framulator"
priority = 5
start = true
task-slots = [{spi_driver = "spi2_driver"}]
stacksize = 2048
notifications = ["hey-you"]
