name = "psc-c-dev"
inherit = ["rev-c.toml", "dev.toml"]

# This writes test data to the FRAM, so if we start actually using the FRAM then
# we should remove this task to avoid clobbering the real data.
[tasks.framulator]
name = "task-framulator"
priority = 5
start = true
task-slots = [{spi_driver = "spi2_driver"}]
stacksize = 2048
notifications = ["hey-you"]
