[package]
name = "task-ping"
version = "0.1.0"
edition = "2024"

[dependencies]
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }
drv-user-leds-api = { path = "../../drv/user-leds-api" }

# Only on the real target; the crate doesn't build for the host.
[target.'cfg(target_os = "none")'.dependencies]
cortex-m = { workspace = true }

[build-dependencies]
build-util = { path = "../../build/util" }
idol.workspace = true

[features]
uart = []
no-ipc-counters = ["idol/no-counters"]

[[bin]]
name = "task-ping"
test = false
doctest = false
bench = false

[lints]
workspace = true
