// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! API crate for the 'attest' task.

#![no_std]

use gateway_messages::AttestError as GwAttestError;
use hubpack::SerializedSize;
use serde::{Deserialize, Serialize};
use userlib::sys_send;

#[derive(
    Copy, Clone, Debug, Deserialize, Eq, PartialEq, Serialize, SerializedSize,
)]
pub enum AttestError {
    CertTooBig,
    InvalidCertIndex,
    NoCerts,
    OutOfRange,
}

impl From<AttestError> for GwAttestError {
    fn from(value: AttestError) -> Self {
        match value {
            AttestError::CertTooBig => Self::CertTooBig,
            AttestError::InvalidCertIndex => Self::InvalidCertIndex,
            AttestError::NoCerts => Self::NoCerts,
            AttestError::OutOfRange => Self::OutOfRange,
        }
    }
}

// struct Attest is defined in the code generated by the IDL.
include!(concat!(env!("OUT_DIR"), "/client_stub.rs"));
