// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! API crate for the root of trust for reporting (RoT-R).

#![no_std]

use derive_idol_err::IdolError;
use userlib::{sys_send, FromPrimitive};

#[repr(u32)]
#[derive(Copy, Clone, Debug, FromPrimitive, Eq, PartialEq, IdolError)]
pub enum AttestError {
    BadSize = 1,
    LogFull = 2,
    Overflow = 3,
    IndexOverflow = 4,

    #[idol(server_death)]
    ServerRestarted,
}

// struct Rotr is defined in the code generated by the IDL.
include!(concat!(env!("OUT_DIR"), "/client_stub.rs"));
