[package]
name = "task-fake-i2c"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = { workspace = true }

drv-i2c-api = { path = "../../drv/i2c-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[[bin]]
name = "task-fake-i2c"
test = false
doctest = false
bench = false

[lints]
workspace = true
