= Interrupts

This chapter discusses the role of CPU interrupts in Hubris and applications.
We'll be using some ARM-inspired terminology, because that's the most mature
Hubris port, but these ideas are intended to translate to RISC-V systems using
controllers like the PLIC.

== Interrupts vs Exceptions

Hubris distinguishes between *interrupts* and *exceptions*. The terminology is
from ARM, but it's a general idea that's also valid on RISC-V.

An _interrupt_ is generated by a peripheral to signal an asynchronous event.
Drivers usually want to find out about some set of interrupts and react to them.

An _exception_ is a broader idea that includes signals generated by the
processor in response to the program's behavior. This would include memory
access violations, illegal instructions, privilege violations, bus faults,
system calls, etc. Exceptions may be asynchronous but are often synchronous.

The kernel provides first-line handlers (interrupt service routines) for all
exceptions, interrupts included, but will also route _interrupts_ to
applications.

== The Hubris interrupt model

We assume an interrupt system with the following characteristics. This is based
on the design of the ARMv6/7/8-M interrupt system, but is intended to be general.

You can likely skip this section if you're not porting the kernel.

- Interrupts can be numbered using small integers starting at zero. They may be
  a subset of exception numbers at a fixed offset -- 16, on ARMvX-M -- and we'll
  subtract that offset when numbering interrupts.

- Interrupts have a "`pending`" flag and an "`enable`" flag. The pending flag
  can be set by hardware at any time, but the ISR will only be invoked if the
  enable and pending flags are set at the same time. (This ensures that
  momentary events are latched and can be handled with a delay.) Starting the
  interrupt service routine clears the "`pending`" flag and may or may not
  affect the "`enable`" flag.

- Interrupt handlers (or interrupt service routines) can be configured not to
  preempt one another, either by configuring priorities in the interrupt
  controller, or by using explicit critical sections in the implementation.
  Hubris runs a quick generic ISR that records an interrupt and returns, so
  nested interrupts are less important. If an interrupt arrives while an ISR is
  running, it should remain pending until the current ISR returns. (This also
  implies that interrupts cannot preempt the kernel, since the kernel always
  runs in interrupt context.)

For brevity in the discussion below, we'll refer to an interrupt "`happening`"
as when the CPU decides to execute the associated in-kernel interrupt service
routine. That can occur when...

- The `pending` bit is set while `enable` was already set.
- The `enable` bit is set when `pending` was previously set.

[#interrupts-from-a-tasks-perspective]
== Interrupts from a task's perspective

The `app.toml` configuration file can route interrupts to tasks, by binding
platform interrupt numbers to _notification sets._ From the task's perspective,
interrupts are delivered as notifications (see the IPC chapter).

Hubris does not allow a single interrupt to be routed to multiple tasks, which
means that a task has exclusive control over any interrupts it handles. Tasks
have access to a syscall, <<sys_irq_control,`irq_control`>>, that they can use to mask and unmask
their interrupts.

When a task starts (or restarts) its interrupts are initially masked. This means
that the hardware `enable` bit is clear, and interrupts can accumulate in the
`pending` bit but will not translate to notifications.

The task can use `irq_control` to unmask (or mask) a subset of its interrupts.
When calling `irq_control`, the task names its interrupts by the notification
bits they will set when they fire, rather than their hardware interrupt numbers.
This means the task can be written to service multiple sources of interrupts
without code changes, only configuration changes. It also removes the need to
validate ownership of the interrupt in the kernel: since tasks can only specify
interrupts using their own notification masks, they can't pick arbitrary IRQ
numbers that might be invalid or owned by someone else.

Once the interrupt is unmasked, `pending` will cause the kernel ISR to fire,
preempting some task code. The only things the ISR does are:

1. Posts the requested notification to the handling task.
2. Masks the interrupt (clearing `enable`).

Once the handling task is waiting in `receive` with the interrupt's notification
bit included in its notification mask, and is the highest priority task that's
ready to go, it will be woken with a notification about the interrupt. It would
normally respond to this by inspecting the hardware to figure out the details of
the event and the next steps required, and then using `irq_control` to unmask
the interrupt again.

In simplified pseudocode, an interrupt handling task's main loop looks something
like this:

[source,rust]
----
// This task only uses notification bit 0 for interrupts.
const MY_INTERRUPT: u32 = 1;

// We're willing to accept interrupts.
sys_irq_control(MY_INTERRUPT, true);

loop {

    // Receive a message -- in this case, we're only
    // expecting notifications.
    let result = sys_recv_closed(
        &mut [],
        MY_INTERRUPT,
        TaskId::KERNEL,
    ).unwrap();

    if result.operation & MY_INTERRUPT != 0 {
        do_interrupt_stuff();
        // Unmask that interrupt so it can fire again.
        sys_irq_control(MY_INTERRUPT, true);
    }
}
----

== Routing interrupts to tasks in the kernel

The kernel has a table of interrupt routing information, filled out at compile
time from the `app.toml`. For each implemented interrupt, it stores two pieces
of information:

- The _index_ of the task that will handle the interrupt.
- The _notification set_ that should be posted to that task when the interrupt
  occurs.

NOTE: Typically an SoC will have many interrupts that are not used by a given
application. We currently store interrupt response information only for the
interrupts that are being used, which makes looking up table entries slightly
slower in exchange for saving a bunch of Flash.

When an interrupt happens, it gets routed to a generic kernel ISR. The kernel
ISR will find the task named in the response record, and post the notification
set. The kernel then clears the interrupt's `enable` bit to prevent reoccurrence
until the task has a chance to respond.

As with any situation where the kernel posts notifications, the kernel exit path
then checks to see if the notification has caused the scheduling situation to
change -- in this case, if the task handling the interrupt is higher priority
than whatever task was running before, and is ready to receive it. If so, the
kernel saves context for the interrupted task and switches to the handler task.

== Kernel reserved interrupts

Some interrupts on some systems cannot be reasonably handled outside the kernel.
In these cases, the kernel will handle them directly, and provide abstractions
if necessary.

The main example here is the system tick timer that is used to maintain the
kernel's internal sense of time, but DMA controllers might also fall into this
category.
