= The Kernel IPC Interface

Hubris provides syscalls for operations that are used by every (or nearly
every) task, and uses IPC for everything else. But IPC is used to talk between
tasks -- what about operations that require the kernel to be involved?

We still use IPC, we just do it with the kernel.

Hubris has a concept called the **virtual kernel task**. The virtual kernel
task is not a real task -- it's an illusion created by the kernel. Any messages
sent to the virtual kernel task will be processed in the kernel itself and
replied to directly.

The kernel answers to the task ID `TaskId::KERNEL` in Rust, which has the
numeric value `0xFFFF`. We chose this number so that the task index portion of
it (in the 10-12 LSBs) would be larger than any valid task index, so there's no
risk of it colliding with an actual task.

== Sending messages to the kernel

The kernel accepts normal IPC messages sent to `TaskId::KERNEL`. Currently, none
of the messages accepted by the kernel make use of leases/borrows, but that's
just because they haven't been useful yet.

The kernel makes a special guarantee: it will respond to IPCs synchronously,
without blocking the sender. This means it is safe to send IPCs to the kernel
from even the highest-priority tasks -- in fact, for the _highest_ priority task
(normally the supervisor), the kernel is the _only_ place it can send messages
safely.

The kernel does not reply to _all_ messages, however. Like making a bogus
syscall, if you send a message to the kernel that uses an out of range selector
or has a very malformatted body, the kernel will deliver a fault to your task
and move on to the next highest priority runnable code.

Messages sent to the kernel, and responses sent back, are formatted using the
`ssmarshal` crate via `serde`. Messages and responses are currently defined as
Rust structs, simply because we haven't had a need to write a supervisor task in
C so far. We may wish to formalize this later, but, this is expedient for now.
Remember when reading the request/response types that it is the `ssmarshal`
serialized form, and not the in-memory layout of the struct, that is exchanged
with the kernel.

The `userlib::kipc` module provides wrapper functions for these IPCs for
programs written in Rust.

NOTE: It is our intent to restrict kernel IPC sends to "`privileged`" tasks --
likely just the supervisor task. We haven't implemented this yet for every
entry point, though some IPC entry points explicitly limit themselves
to the supervisor.

=== `read_task_status` (1)

Reads out status information about a task, _by index._ This is intended to be
used for task management purposes by the supervisor -- because tasks can restart
whenever, the supervisor generally doesn't want to concern itself with getting
generation numbers right.

==== Request

[source,rust]
----
struct TaskStatusRequest {
    task_index: u32,
}
----

==== Preconditions

The `task_index` must be a valid index for this system.

==== Response

[source,rust]
----
type TaskStatusResponse = abi::TaskState;
----

==== Notes

See the `abi` crate for the definition of `TaskState` that matches your kernel.
Here is a representative example at the time of this writing:

[source,rust]
----
pub enum TaskState {
    /// Task is healthy and can be scheduled subject to the `SchedState`
    /// requirements.
    Healthy(SchedState),
    /// Task has been stopped by a fault and must not be scheduled without
    /// intervention.
    Faulted {
        /// Information about the fault.
        fault: FaultInfo,
        /// Record of the previous healthy state at the time the fault was
        /// taken.
        original_state: SchedState,
    },
}

pub enum FaultInfo {
    StackOverflow { address: u32 },
    // other fault cases go here
}

pub enum SchedState {
    /// This task is ignored for scheduling purposes.
    Stopped,
    /// This task could be scheduled on the CPU.
    Runnable,
    /// This task is blocked waiting to deliver a message to the given task.
    InSend(TaskId),
    /// This task is blocked waiting for a reply from the given task.
    InReply(TaskId),
    /// This task is blocked waiting for messages, either from any source
    /// (`None`) or from a particular sender only.
    InRecv(Option<TaskId>),
}
----

=== `reinit_task` (2)

Reinitializes a task, chosen by index, and optionally starts it running.

This is valid in any task state, and can be used to interrupt otherwise
uninterruptible operations like the SEND syscall.

A successful call to `reinit_task` has the following effects:

1. The targeted task is forced out of whatever state it was in, and left in
either the `Stopped` (if `start` is `false`) or `Runnable` (if `start` is
`true`) state.

2. The task's generation number is incremented.

3. The task's registers are reset (to particular values where necessary, and to
zero otherwise) and the stack erased.

4. The task's interrupts are disabled and its timer is stopped.

5. Any _other_ tasks that were blocked in IPC with the targeted task (either
waiting to deliver a message, waiting for a reply to a delivered message, or
waiting to receive) are interrupted and given a <<death,dead code>> to indicate
that the IPC will never complete.  The dead code's generation is the *new*
generation number for the faulted task.

==== Request

[source,rust]
----
struct ReinitRequest {
    task_index: u32,
    start: bool,
}
----

==== Preconditions

The `task_index` must be a valid index for this system.

==== Response

[source,rust]
----
type ReinitResponse = ();
----

==== Notes

If a task asks to reinit _itself,_ the kernel mumbles "`alright, your funeral`"
and reinits the caller. Given that `reinit_task` is intended to be restricted to
the supervisor, and the supervisor can't `panic!` to restart without taking out
the system, this seemingly weird move may actually prove useful.

Reinitialization _does not_ write over the task's memory except for the stack.
Tasks are responsible for (say) setting up their data/BSS areas on start. This
is explicitly intended to allow tasks to keep some information from "`past
lives`" if required.

=== `fault_task` (3)

Forces a task into a `Faulted` state. Specifically, this will set the task's
fault to `FaultInfo::Injected(caller)`, where `caller` is the TaskId of the task
that called `fault_task` (i.e. you). This means that a fault caused by
`fault_task` is both easily distinguished from any other fault, and traceable.

`fault_task` immediately prevents the targeted task from running, and any
_other_ tasks that were blocked in IPC with the targeted task are interrupted
and given a <<death,dead code>> to indicate that the IPC will never complete.

==== Request

[source,rust]
----
struct FaultRequest {
    task_index: u32,
}
----

==== Preconditions

The `task_index` must be a valid index for this system.

==== Response

[source,rust]
----
type FaultResponse = ();
----

==== Notes

As with `reinit_task`, it is possible for a task to use `fault_task` to fault
_itself._ This is an odd thing to do.

On faults, the kernel tries to save the pre-fault state of the task. However, if
you apply `fault_task` to an already-faulted task, the task will be marked as
double-faulted and the previous fault will be replaced with the new injected
fault.

=== `read_image_id` (4)
=== `reset` (5)
=== `get_task_dump_region` (6)

A dump region is an area of memory for a specified task that can be
read by the supervisor for purpose of creating a memory dump for debugging.
For a specified task and region index, `get_task_dump_region`
will return the details of the dump region, if any.  This entry point
is only present if the kernel's `dump` feature is enabled.

==== Request

[source,rust]
----
type GetTaskDumpRegionRequest = (u32, u32);
----

==== Preconditions

The task index (`GetTaskDumpRegionRequest.0`) must be a valid task index.  The
dump region index (`GetTaskDumpRegionRequest.1`) should denote the region of
interest.

==== Response

[source,rust]
----
struct TaskDumpRegion {
    base: u32,
    size: u32,
}

type GetTaskDumpRegionResponse = Option<TaskDumpRegion>;
----

==== Notes

For the specified task index, this will return the dump region specified by
the dump region index.  If the dump region index is equal to or greater
than the number of dump regions for the specified task, `None` will
be returned.

=== `read_task_dump_region` (7)

For a given task and task dump region, this will read the specified region and
return its contents.  The region should be entirely contained by a region that
has been returned by a call to `get_task_dump_region` but is otherwise
unconstrained.  This entry point is only present if the kernel's `dump`
feature is enabled.

==== Request

[source,rust]
----
struct TaskDumpRegion {
    base: u32,
    size: u32,
}

type ReadTaskDumpRegionRequest = (u32, TaskDumpRegion);
----

==== Preconditions

The task index (`ReadTaskDumpRegionRequest.0`) must be a valid task index.
The dump region should be entirely contained by a region that has been
returned by a call to `get_task_dump_region` for the specified task.

==== Response

A copy of the memory referred to by the specified region, starting
at `base` and running for `size` bytes.

=== `software_irq` (8)

For a given task index and a notification mask for that task, this will
trigger software interrupts for any IRQ(s) mapped to bits in that task's
notification set.

Any interrupts triggered through this mechanism will be delivered to the
that task identically to an actual hardware interrupt, as described in
the <<interrupts-from-a-tasks-perspective,the documentation on interrupts>>.

==== Request

[source,rust]
----
type SoftwareIrqRequest = (u32, u32);
----

==== Preconditions

The task index (`SoftwareIrqRequest.0`) must be a valid task index.

The notification mask (`SoftwareIrqRequest.1`) should be a valid notification
mask for the specified task, and should have at least one bit set. Any bits
set in the notification mask should be assigned to hardware interrupts in
the task's build-time configuration.

The caller *must* be the supervisor (task index 0).

==== Response

[source,rust]
----
type SoftwareIrqResponse = ();
----

==== Notes

This interface is primarily intended for testing interrupt handling, and can
only be called by a task running as the supervisor. When this KIPC is called,
an actual machine interrupt is triggered for the relevant hardware interrupt
source. The kernel then responds to the interrupt using its normal
interrupt-handling infrastructure, which dispatches a notification to the 
subscribed task.

This KIPC is *not* intended for use as a general-purpose inter-task signalling
mechanism. For that purpose, a <<notifications,notification>> should be used
instead.

=== `find_faulted_task` (9)

Scans forward from a given task index searching for a faulted task. If a faulted
task is found, returns its index. Otherwise, returns zero, the index of the
supervisor task, which is by definition not faulted.

To simplify supervisor implementations, the given task index may equal the
number of tasks in the system. In this case, there are no tasks to search, and
you always get zero back.

We do _not_ permit greater indices than that, because that would strongly
suggest a bug.

==== Request

[source,rust]
----
struct FindFaultedTaskRequest {
    starting_index: u32,
}
----

==== Preconditions

The `starting_index` must be a valid index for this system, or one greater.

==== Response

[source,rust]
----
struct FindFaultedTaskResponse {
    fault_index: u32,
}
----

==== Notes

This is intended for the common case of a supervisor scanning the task table in
search of a fault. Compared to doing this manually with `read_task_status`,
`find_faulted_task` has several advantages:

1. Generates one kipc per failed task, plus one, rather than one kipc per
   potentially failed task.

2. Avoids serializing/transferring/deserializing the relatively complex
   `TaskState` type, which supervisors rarely make use of in practice.

3. Can be implemented in a way that doesn't potentially panic the supervisor.

The "task ID or zero" return value is represented as an `Option<NonZeroUsize>`
in the Rust API, so a typical use of this kipc looks like:

[source,rust]
----
let mut next_task = 1; // skip supervisor
while let Some(fault) = kipc::find_faulted_task(next_task) {
    let fault = usize::from(fault);
    // do things with the faulted task

    next_task = fault + 1;
}
----

=== `read_panic_message` (10)

If the task with the requested index is in the faulted state due to a panic,
reads the contents of its panic message into the response buffer.

==== Request

[source,rust]
----
struct ReadPanicMessageRequest {
    task_index: u32,
}
----

==== Preconditions

`task_index` must be a valid task index for this system.

==== Response

[source,rust]
----
Result<&[u8], abi::ReadPanicMessageError>
----

==== Notes

If the requested task is not currently in the faulted state due to a panic,
this KIPC returns the `abi::ReadPanicMessageError::TaskNotPanicked` response code.

If the requested task has panicked, but the buffer containing its panic
message is invalid, this KIPC returns the
`abi::ReadPanicMessageError::BadPanicMessage` response code. If the target task
uses the panic handler provided by the `userlib` crate, this should not be
possible. However, it may occur if a task calls the `sys_panic` syscall
directly with invalid arguments, such as a slice pointing outside the task's memory.

The panic message is truncated to the length of the response buffer. Since
Hubris only stores the first 128 bytes of panic messages, a 128-byte response
buffer will normally not result in further truncation.

The panic message is normally UTF-8. However, because of this byte-based truncation, and because the panic message is coming from a failing task in the first place, be careful not to *assume* that the panic message is valid UTF-8. See the `<[u8]>::utf8_chunks` function for one possible method of handling the panic message safely.
== Receiving from the kernel

The kernel never sends messages to tasks. It's simply not equipped to do so.
However, it is legal to enter a closed receive from the kernel. This might be
counter-intuitive -- since the kernel will never send a message for you to
receive, it sure sounds like a programming error, and Hubris as a rule tries to
turn obvious programming errors into crashes.

Receiving from the kernel is deliberately allowed to enable two use cases:

1. **Blocking the current task until a notification arrives while ignoring all
incoming messages.** By receiving from the kernel's task ID with a non-zero
notification mask, the current task will wait until any matching notification
arrives.

2. **Halting the current task.** If you really want to stop the current task
forever (or at least, until the supervisor reinits it), you can receive from the
kernel with _no_ notification mask bits set.

NOTE: We haven't needed that second one in practice, so we might make it an
error someday. The first one, on the other hand, is useful.
