= Startup

This document describes how Hubris takes a CPU from reset to running your
application. It is mostly architecture-neutral; any architecture-specific bits
will be called out.

== From reset to Rust

At reset, the processor runs a designated chunk of code, the *reset handler.*
Hubris's reset handler is responsible for making the world safe for Rust code.
This means:

- Setting up a stack pointer, if the hardware doesn't do that for us;

- Enabling any processor features or memory devices required to run the kernel
  -- for example, if the device has an FPU, we need it turned on so we can
  configure it even though the kernel itself may not use floating point;

- Ensuring that all initialized variables get initialized;

- Jumping to `main`.

On ARMv6-M, ARMv7-M, and ARMv8-M this sequence is handled by the `cortex_m_rt`
crate, which in turn uses the `r0` crate to set up Rust variables.

== `main`: bring your own

Currently, Hubris expects the application packager (i.e. you) to provide a
`main` routine in the crate that builds the kernel. This gives you an
opportunity to do any setup that isn't handled by the runtime startup, but needs
to happen before the kernel boots.

`main` should do those things, and then call `start_kernel`.

This same file is where you might declare interrupt service routines for any
SoC-specific interrupts that you wish to handle outside Hubris's standard
mechanism -- for cases where an interrupt is so latency-sensitive that you need
to handle it with a privileged ISR, despite the safety implications. Hubris's
internal ISR symbols are weak, so, declaring an ISR in this file overrides them.

== Starting the kernel

The kernel expects to be packaged in Flash with a table describing the tasks.
This table would normally immediately follow the kernel image, though it can be
placed anywhere; `main` hands its address into `start_kernel`.

The table consists of the following (all the types named here are defined in
the `abi` crate):

- An `App` header record describing the overall shape of things to come.
- One or more region descriptor (`RegionDesc`) records, carving up address space
  into regions with attributes.
- One or more task descriptor (`TaskDesc`) records describing tasks.

TIP: Region descriptors can technically be shared among tasks -- task
descriptors specify the regions they can access by _index_. Task descriptors
contain the initial program counter and stack pointer values for the task,
which will be loaded into those registers when the task first runs (or is
restarted). Hubris will check that those pointers fall within some memory
region, but other than that, the layout of your task memory regions and their
roles is totally up to you. This means you _could_ create an application with
tasks that share a Flash code region, for instance, though, think carefully
before doing so.

`start_kernel` reads the `App` header and the task and region descriptors,
validates their integrity, and allocates RAM. This is the only time the kernel
allocates RAM, and it allocates it from a single contiguous area delimited by
the `hubris_kernel_ram_start` and `hubris_kernel_ram_end` symbols. (This area of
memory should not overlap any of your application memory regions.)

In this memory area, the kernel allocates bookkeeping information for each task
described in the task table. The few kernel global variables are *not* placed
here; it's only used for stuff that is dynamically sized based on information
found in the `App` header.

If the kernel cannot allocate bookkeeping structures for the tasks described in
the descriptor tables, it will panic.

Any extra RAM allocated to the kernel, but not used, is lost.

== Starting the first task(s)

One of the fields in the task descriptor contains a `START_AT_BOOT` flag. Any
task with this flag set will be initialized in `Runnable` state; all others are
initialized in `Stopped` state. (The `START_AT_BOOT` flag in the descriptor
corresponds to the `start = true` field in the `app.toml`.)

As its last act during startup, the kernel scans the tasks looking for the
*highest priority* task marked `START_AT_BOOT`. It then switches into that task,
and your application is running.

If the task descriptor table contains *zero* tasks marked `START_AT_BOOT`, this
represents an application configuration error, and the kernel will panic.
