:toc:

= Hubris Syscalls

Syscalls provide ways for tasks to invoke kernel code. Hubris has a very small
set of syscalls, because syscalls -- unlike IPC -- have to be implemented in the
kernel and are hard to proxy, so they form an ongoing ABI commitment.

In general, the following sorts of things are syscalls (exhaustive):

* IPC primitives
** Send, Receive, Reply
** Access to memory borrowed from senders
** Looking up the correct generation number for a task
* Access to the multiplexed per-task timer
* Control of the current task's interrupt mask
* Crashing the current task

And the following sorts of things are not (not exhaustive):

* Checking the state or fault information of a task
* Starting/restarting a task
* Forcing faults on other tasks

This is because the things in the _first_ category are universal, or nearly so,
while the things in the _second_ category are normally used only in special
cases, usually by the supervisor task.

In general, syscalls should represent *operations that every task should have
access to,* while anything privileged or sensitive should be done through IPC.

This doesn't mean all these things need to be done outside the kernel, though.
We have an escape hatch, in the form of messages to the virtual "`kernel
task.`" The kernel IPC interface is the topic of the next chapter.

== Syscall ABI

Syscalls are invoked using the architecture's supervisor-call instruction or
equivalent.

We'll describe syscalls in an architecture-independent manner below by referring
to abstract *argument and return slots* instead of register names. Syscalls have
seven argument slots and eight return slots.

We assume that all registers are 32 bits wide.

=== ARMv6-M / ARMv7-M / ARMv8-M

Syscalls are invoked using the `SVC` instruction. The 8-bit immediate in the
instruction is ignored, because reading it from user text is potentially
sketchy.

Syscalls provide for up to 7 arguments and 8 return values in registers.
Syscalls never use arguments from the stack, to make it easier to reason about
possible memory management faults during syscall entry (i.e. now there aren't
any).

Arguments to syscalls are passed in `r4` through `r10`, with the syscall index
in `r11`.

Return values from syscalls are returned in `r4` through `r11`.

NOTE: You're probably wondering why we're using weird registers instead of the
standard calling convention, which would pass things in `r0` through `r3`. It
comes back to the point above about stack accesses. The ARMvX-M hardware stores
`r0` through `r3` _on the user stack_ on entry to a syscall, and we don't want
to have to read it back from there. `r4` through `r11`, on the other hand, are
treated as callee-save, and our syscall entry sequence saves them into the TCB,
where we can refer to them as needed.

NOTE: This calling convention is somewhat awkward on ARMv6-M, where the
registers above `r7` are second-class. So it goes.

=== RISC-V

Syscalls are invoked using the `ECALL` instruction. The rest is TBD.

== Syscalls

[#sys_send]
=== `SEND` (0)

Sends a message.

The error-free path:

- Identifies the desired recipient.
- Transfers a message (0+ bytes) from an outgoing slice in your task's memory,
  into an incoming slice in the recipient's memory.
- Waits until the recipient calls `REPLY`.
- During this time, allows the recipient to access your task's memory, subject
  to the rules laid out in the lease table.
- Once `REPLY` happens, transfers the reply from the recipient's memory into the
  reply buffer slice in your task's memory.
- Resumes your task.

==== Arguments

* 0: packed target and operation.
** Bits 31:16: target task ID (split into index and generation per the constants
   in the `abi` crate).
** Bits 15:0: operation code (application defined).
* 1: Base address of outgoing message.
* 2: Length of outgoing message, in bytes.
* 3: Base address of buffer where a reply should be deposited.
* 4: Size of reply buffer, in bytes.
* 5: Base address of lease table.
* 6: Number of leases in lease table.

==== Lease table layout

Each lease is 12 bytes in size and must be 4-byte aligned. A lease is equivalent
to the following Rust struct:

[source,rust]
----
#[repr(C)]
struct Lease {
    attributes: u32,
    base_address: usize,
    length: usize,
}

const ATT_READ: u32 = 1 << 0;
const ATT_WRITE: u32 = 1 << 1;
----

- `attributes` can specify that a lease can be read from, written to, or both.
  Any use of undefined attribute bits will cause a fault.
- `base_address` is a byte-aligned address. If this points to memory your task
  can't access, it will cause a fault.
- `length` is the length of the leased memory region in bytes.

==== Return values

- 0: response code (application defined with caveat below).
- 1: length of reply deposited into reply buffer.

==== Faults

Most things that can go wrong with `SEND` are programming errors, and will cause
your task to be immediately faulted instead of returning a code.

|===
| Condition | Fault taken

| Recipient forbidden by your task's (static) IPC mask.
| `BadInteraction`

| Recipient task index greater than the (static) number of tasks in the entire
  system.
| `TaskOutOfRange`

| Any slice invalid (e.g. it would wrap the end of the address space).
| `InvalidSlice`

| Lease table slice misaligned.
| `InvalidSlice`

| Outgoing slice or lease table are memory you can't actually read.
| `MemoryAccess`

| Reply buffer slice is memory you can't actually write.
| `MemoryAccess`

|===

==== Notes

Target and operation are packed into a single word because we're out of useful
registers on ARM. This currently limits operation codes to 16 bits. We might
revisit this later.

For all slices (outgoing message, reply buffer, lease table), if the count is
zero, the base address won't be dereferenced and can be illegal. In particular,
it's okay to pass address 0 for empty slices.

If the slices are *not* zero length, however, the kernel will check them against
your task's memory map, and your task will be faulted if anything is amiss.

Slices are accessed by the kernel *only* while your task is blocked in `SEND`,
so passing a slice to the kernel here can be done safely (in the Rust sense).
The reply buffer slice must be an `&mut`, but the others can be `&`.

The lease table slice must be 4-byte aligned. The others can be arbitrarily
aligned.

Response codes are application defined except for one subtlety: *dead codes.*
The kernel will deliver a dead code in two situations:

1. SEND to a task with the wrong generation, suggesting that the recipient has
   restarted without the sender noticing.

2. If the recipient crashes while the sender is waiting -- either waiting to
   transfer the initial message, or waiting for the reply.

Dead codes have their top 24 bits set (that is, `0xFFFF_FF00`). In the bottom 8
bits, the kernel returns the _current_ generation number of the peer, so that
the caller can correct their records.

It is possible to fake a dead task by deliberately sending a response code in
the dead code range -- because it didn't seem useful to spend cycles filtering
this out.

[#sys_recv]
=== `RECV` (1)

Receives a pending message or notification.

The error-free path:

- Blocks until some number of tasks are ready to send to your task.
- Picks the highest priority one.
- Transfers its message into memory you've designated.
- Keeps the sending task blocked.
- Returns information describing the message to your task.

If the provided notification mask is not zero, the receive operation may be
interrupted by a _notification message_ from the kernel instead. This happens
if any of the notification bits specified in the mask (by 1 bits) have been set
on the calling task. When RECV returns, you can distinguish these notification
messages because they have the kernel's virtual task ID `0xFFFF` as the message
sender.

==== Closed vs Open RECV

One argument to RECV determines whether to accept messages from _any_ sender, or
to only accept messages from _one._ Accepting messages from any sender is called
an "`open`" receive, while only listening for one sender is "`closed.`"

During an open receive, a task may receive messages sent by any other task, plus
any notifications enabled by the notification mask.

During a closed receive, a task will receive messages only from the chosen task.
The task will still receive any notifications set in its notification mask.

To listen *only* for notifications, a task can perform a closed receive against
the kernel's task ID, `0xFFFF`.

==== Arguments

- 0: Address of a buffer where received messages should be written.
- 1: Number of bytes in that buffer.
- 2: Notification mask to apply during this receive.
- 3: Sender filter for open vs closed receive.
** Bit 31: 0=open, 1=closed
** Bits 30:16: reserved
** Bits 15:0: TaskId if closed, ignored if open.

==== Return values

- 0: always 0 for open receive; closed receive may also return a *dead code*
  (see `SEND`) to indicate that the chosen peer has died.
- 1: Task ID of the sender (generation in 15:12, ID in 11:0).
- 2: Operation code used by sender. (Or notification bits, if the sender is the
  kernel.)
- 3: Length of message sent, in bytes. This may be longer than the buffer
  provided by the caller, which indicates that the message was truncated.
- 4: Number of bytes of room the caller has provided for the reply message.
- 5: Number of leases provided with message.

==== Faults

Most things that can go wrong with `RECV` are programming errors, and will cause
your task to be immediately faulted instead of returning a code.

|===
| Condition | Fault taken

| Receive buffer slice invalid (i.e. would wrap the end of the address space).
| `InvalidSlice`

| Receive buffer slice is memory you can't actually write.
| `MemoryAccess`

|===

==== Notes

It's legal to specify a zero-length receive buffer, if the messages you're
expecting consist only of the operation code or notification bits. In this
case, the base address is ignored and may be invalid or null.

If the sender sent a message _longer_ than your receive buffer, you will get the
_prefix_ of the message, and the returned response length will give the _actual_
length. This means you should check the response length against your buffer
length to detect truncation.

Leases received with the message are referenced with the combination (TaskID,
lease number). Lease numbers range between 0 and one less than the received
lease count, as you'd expect. Leases are only valid until the sending task
unblocks, which normally happens only when you `REPLY`, but could also occur as
a result of an asynchronous restart from the supervisor.

The notification mask is provided anew with each receive because the `RECV`
callsite has a clear idea of which notifications it can handle. Plus, it saves a
syscall during the common pattern of updating the mask and then receiving.

`RECV` is called `RECV` because Cliff can't spell "`recieve`" reliably.

[#sys_reply]
=== `REPLY` (2)

Replies to a received message.

If all goes well, this copies a slice of data from your task's memory into the
caller's memory and resumes the caller.

==== Arguments

- 0: Task ID of sender we're replying to.
- 1: Response code to deliver.
- 2: Base address of reply message.
- 3: Number of bytes in reply message.

==== Return values

`REPLY` doesn't return anything, but should be treated as clobbering return
registers 0 and 1 for future compatibility.

==== Faults

There is only one way to break `REPLY`, and that's with a bogus slice.

|===
| Condition | Fault taken

| Outgoing buffer slice invalid (i.e. would wrap the end of the address space).
| `InvalidSlice`

| Outgoing buffer slice is memory you can't actually read.
| `MemoryAccess`

| Reply message is longer than recipient requested.
| `ReplyTooBig`

|===

==== Notes

It might strike you as odd that `REPLY` doesn't return any status. This is a
subtle decision, and has to do with what servers will do if their clients
"`defect`" or crash before reply (generally: nothing).

Reply messages can be zero-length, in which case the base address of the slice
is ignored. Often, the response code is enough.

`RECV` delivers the size of the caller's response buffer, so your task has
sufficient information to not overflow it. If the caller's response buffer is
too small, you are expected to instead use `REPLY_FAULT` with the
`ReplyBufferTooSmall` code. If you instead send a reply that won't fit, that's
treated as a programming error in your task, and you take a `ReplyTooBig` fault.

[#sys_set_timer]
=== `SET_TIMER` (3)

Configures your task's timer.

==== Arguments

- 0: Enable (1) or disable (0) flag.
- 1: Low 32 bits of deadline.
- 2: High 32 bits of deadline.
- 3: Notification bitmask to post when timer expires.

==== Return values

None. All registers preserved.

==== Faults

None.

==== Notes

The notification bitmask will be delivered into your task's notification set
when the kernel time becomes equal to or greater than the given deadline, if the
timer is enabled. Configuring the timer with an enabled deadline that is already
in the past delivers the notification immediately (though you won't notice until
you `RECV`).

The time unit for deadlines is not currently specified -- it's currently an
abstract "`kernel ticks`" unit. This will be fixed.

[#sys_borrow_read]
=== `BORROW_READ` (4)

Copies data from memory borrowed from a caller (a "`borrow`").

==== Arguments

- 0: TaskId of lender.
- 1: Lease index for that lender.
- 2: Offset within the borrowed memory to start reading.
- 3: Base address of slice in your memory space to deposit data.
- 4: Length of slice in bytes.

==== Return values

- 0: response code: zero on success, non-zero if something went wrong on the
  sender side.
- 1: on success, number of bytes copied.

==== Faults

TBD

==== Notes

This provides "`file-like`" access to memory borrowed from other tasks, rather
than direct memory-mapped access, and that's for a good reason: the other task
may potentially be restarted at any time. In the event that the peer restarts
while you're working with one of its borrows, you'll get an error return code
and can clean up -- whereas if you were directly accessing its memory, we'd
have no choice but to deliver a fault to stop you. That would give clients the
opportunity to induce faults in shared servers, which would be bad.

[#sys_borrow_write]
=== `BORROW_WRITE` (5)

Copies data into memory borrowed from a caller (a "`borrow`").

==== Arguments

- 0: TaskId of lender.
- 1: Lease index for that lender.
- 2: Offset within the borrowed memory to start writing.
- 3: Base address of data (in your memory space) to transfer.
- 4: Length of data in bytes.

==== Return values

- 0: response code: zero on success, non-zero if something went wrong on the
  sender side.
- 1: on success, number of bytes copied.

==== Faults

TBD

==== Notes

This provides "`file-like`" access to memory borrowed from other tasks, rather
than direct memory-mapped access, and that's for a good reason: the other task
may potentially be restarted at any time. In the event that the peer restarts
while you're working with one of its borrows, you'll get an error return code
and can clean up -- whereas if you were directly accessing its memory, we'd
have no choice but to deliver a fault to stop you. That would give clients the
opportunity to induce faults in shared servers, which would be bad.

[#sys_borrow_info]
=== `BORROW_INFO` (6)

Collects information about one entry in a sender's lease table.

==== Arguments

- 0: TaskId of lender.
- 1: Lease index for that lender.

==== Return values

- 0: response code: zero on success, non-zero if something went wrong on the
  sender side.
- 1: attributes field (see `SEND` for definition of lease table attributes).
- 2: length in bytes

[#sys_irq_control]
=== `IRQ_CONTROL` (7)

==== Arguments

- 0: notification bitmask corresponding to the interrupt
- 1: desired state
** bit 0: 0 = disabled, 1 = enabled
** bit 1: 0 = leave pending, 1 = clear pending

==== Return values

None.

==== Faults

|===
| Condition | Fault taken

| The given notification bitmask is not mapped to an interrupt in this task.
| `NoIrq`

|===

==== Notes

It might seem strange that this syscall has tasks refer to interrupts using
their notification bits. However, this is quite deliberate, for two reasons:

1. It gives tasks a consistent semantic model. When an interrupt goes off, they
   see a notification in bit X; when they want to re-enable that interrupt,
   they request enabling on bit X. There is no separate "`IRQ number`" to
   configure; that's left to the application-level config file.

2. It makes it impossible for a task to mess with other tasks' interrupts,
   since it can only refer to its _own_ mapped interrupts, by construction.

The concept of a "pending" interrupt is inherently specific to a particular
architecture and interrupt controller. On an architecture without a concept of
pending interrupts, bit 1 has no effect. However, on architectures with
level-triggered interrupts from peripherals and a concept of "pending"
interrupts, clearing the pending status when re-enabling may be important for
avoiding a duplicate notification.

=== `PANIC` (8)

Delivers a `Panic` fault to the calling task, recording an optional message.

This is roughly equivalent to the Rust `panic!` operation and is used in its
implementation.

==== Arguments

- 0: base address of 7-bit ASCII panic message
- 1: length of panic message in bytes

==== Return values

Does not return.

==== Faults

This produces a `Panic` fault every time -- that's its purpose.

==== Notes

The kernel does not interpret the panic message in any way, but may be made
available to the supervisor if it asks.

[#sys_get_timer]
=== `GET_TIMER` (9)

Reads the contents of the task's timer: both the current time, and any
configured deadline.

==== Arguments

None.

==== Return values

- 0: low 32 bits of kernel timestamp.
- 1: high 32 bits of kernel timestamp.
- 2: 0=no deadline set, 1=deadline set.
- 3: low 32 bits of deadline, if set.
- 4: high 32 bits of deadline, if set.
- 5: notifications to post when deadline reached.

==== Faults

None.

==== Notes

The timestamp is defined as being CPU-wide, consistent for all tasks, so the
result of this syscall can be meaningfully sent to other tasks on the same CPU.
(Behavior in multicore situations is not yet defined.)

The time unit is not currently specified -- it's currently an abstract "`kernel
ticks`" unit. This will be fixed.

=== `REFRESH_TASK_ID` (10)

Given a task ID that may have the wrong generation, produces a corrected task
ID with the target task's current generation.

This is intended for two use cases:

1. Initially contacting a task. In this case, the generation can be arbitrary
   and is usually given as zero.

2. Recovering from a peer task crashing. In this case, hand in your previously
   valid TaskId to redeem it for a new one.

==== Arguments

- 0: task ID (in low 16 bits)

==== Return values

- 0: task ID (in low 16 bits), top 16 bits zeroed

==== Faults

|===
| Condition | Fault taken

| Recipient task index greater than the (static) number of tasks in the entire
  system.
| `TaskOutOfRange`

|===

=== `POST` (11)

Accumulates a set of notification bits into another task's notification word
using bitwise OR. This enables a simple inter-task asynchronous communication
mechanism. See <<notifications>> for more information on the mechanism.

==== Arguments

- 0: task ID (in low 16 bits)
- 1: bits to OR in

==== Return values

- 0: zero on success, dead code on generation mismatch.

==== Faults

|===
| Condition | Fault taken

| Recipient task index greater than the (static) number of tasks in the entire
  system.
| `TaskOutOfRange`

|===

==== Notes

If the task generation is wrong, the caller will receive a dead code (see
<<death>>) and no notification will be posted.

If the task being notified is higher priority, and the notification causes it
to wake, control will immediately transfer to the higher priority task. This
will be returned as "`success`" to the caller, because the notification was
successfully delivered, even if the higher priority task subsequently crashes
before the caller gets another chance to run.


=== `REPLY_FAULT` (12)

Like `REPLY`, this resumes a task that is blocked waiting for a reply from the
invoking task. Unlike `REPLY`, this does not set the task runnable, and instead
marks it as faulted by a recognizable code.

==== Arguments

- 0: task ID (in low 16 bits)
- 1: `ReplyFaultReason` value (see `abi` crate)

==== Return values

`REPLY_FAULT` doesn't return anything, but should be treated as clobbering
return registers 0 and 1 for future compatibility.

==== Faults

|===
| Condition | Fault taken

| Designated task index greater than the (static) number of tasks in the entire
  system.
| `TaskOutOfRange`

| `ReplyFaultReason` value undefined in `abi` enum.
| `BadReplyFaultReason`

|===

==== Notes

Like `REPLY`, this syscall just silently ignores replies to the wrong
generation, under the assumption that the task got restarted for some reason
while we were processing its request. (It can happen.)

[#sys_irq_status]
=== `IRQ_STATUS` (13)

Returns the current status of interrupts mapped to the calling task.

==== Arguments

- 0: notification bitmask corresponding to the interrupt(s) to query

==== Return values

- 0: an `IrqStatus` (see the `abi` crate) describing the status of the
  interrupts in the notification mask. Currently, the following bits in
  `IrqStatus` are significant:
  ** `0b0001`: set if any interrupt in the mask is enabled
  ** `0b0010`: set if an IRQ is pending for any interrupt in the mask
  ** `0b0100`: set if a notification has been posted to the caller but
     not yet consumed

==== Faults

|===
| Condition | Fault taken

| The given notification bitmask is not mapped to an interrupt in this task.
| `NoIrq`

|===

==== Notes

As discussed in the notes for the <<sys_irq_control, IRQ_CONTROL>> syscall,
tasks refer to interrupts using their notification bits.

If the provided notification mask is zero, the syscall will return a `NoIrq`
fault. If the provided notification mask has multiple bits set, the returned
`IrqStatus` value will be the boolean OR of the status of all interrupts in the
map (e.g. if any interrupt in the mask is pending, the `PENDING` bit will be
set, and so on).
