[#timers]
= Timers

In addition to fancier hardware timers, the microcontrollers we target tend to
have a single general-use timer that is portable across implementations and
silicon vendors -- the `SysTick` on ARM, the `mtimer` on RISC-V. Hubris provides
a multiplexer for this timer, so that each task appears to have its own.

The time unit of the clock is selectable by the application, but in practice, we
always select milliseconds. This chapter will refer to the clock unit as
milliseconds.

== Timestamp format

Hubris timestamps are from a monotonic realtime clock. Time is kept since kernel
startup, which presumably corresponds to the most recent CPU reset or bootloader
exit. Without outside information (such as data from an external RTC) there's no
way to map a Hubris timestamp to human wall time -- they're mostly used for
relative delays.

When interacting with the kernel, timestamps are expressed as milliseconds in
`u64` format. This means the timer will roll over after a bit more than 584
million years of continuous operation. The intent is that applications need not
concern themselves with timer wraparound, because reasoning about timer
wraparound is hard.

The kernel reserves the right to keep time in a different format internally.

== Programmer's model

Each task gets a timer. The timer has three properties:

- An _enable bit._
- A _deadline._
- A _notification set._

At periodic intervals (ticks), if the enable bit is set, the kernel checks the
deadline to see if it is in the future. If not (it is `\<=` the current time),
the kernel will

- Clear the enable bit.
- Post the notification set to the owning task. (Notifications are discussed in
  more detail in <<notifications>>.)

The task will find out about this next time it enters `recv` with the
notification bits unmasked -- or immediately, if the task is already blocked in
`recv` at the time the timer fires.

Because the enable bit is cleared when the timer fires, tasks can assume that
setting their timer will result in exactly zero or one notification events.

NOTE: If a task sets the timer notification set to `0`, it will not receive a
notification when the timer fires, but it could still poll the enable bit. We
haven't had a use for this so far, but, now you know.

By default, when a task is initialized, its timer is set up as:

- Enable bit clear.
- Deadline `!0` (i.e. the distant future)
- Notification set `0` (i.e. no bits)

== Timer control operations

Tasks access their timers through a pair of syscalls,
<<sys_set_timer,`set_timer`>> and <<sys_get_timer,`get_timer`>>. `get_timer` is
overloaded to return both the current kernel time and the contents of the task's
timer -- this is convenient because it ensures that both were observed at the
same (kernel) time.

== Using the timer to implement `sleep`

The most common use of the task timer is to implement a delay. If this is _all_
you're doing -- i.e. you don't have several deadlines to juggle -- then it's
fairly easy:

1. Choose a notification bit that isn't used for other purposes.
2. Set the timer for the desired wake time.
3. Enter a _closed receive_ from only the kernel's TaskId, giving a notification
mask with only the chosen bit set.

During this sleep, incoming messages will queue, and other notification bits
will accumulate, but the task will only wake when the deadline is reached.

The `userlib` crate provides an implementation of this using notification bit 31
in the `userlib::hl` module.

== Multiplexing your multiplexed timer

If a task needs to track multiple delays, it will need to maintain some
in-memory data structure (such as a table or heap) tracking their deadlines. At
any given time, the kernel-provided timer should be set to the _lowest_
deadline. When it fires, take action and then load the next lowest. And so
forth.

The `multitimer` crate implements such a multiplexed timer.
