= Timers

Hubris provides kernel-level support for multiplexing the system tick timer,
allowing each task to pretend it has its own copy.

On ARM, this uses the `SysTick` peripheral. On RISC-V, this uses the `mtimer`.

== Timestamp format

Time is kept since kernel startup, which presumably corresponds to the most
recent CPU reset.

When interacting with the kernel, timestamps are expressed as nanoseconds in
`u64` format. This means the timer will roll over after a bit more than 584
years of continuous operation. The intent is that applications need not concern
themselves with timer wraparound, because reasoning about timer wraparound is
hard.

Internally, the kernel will probably keep time in a different format, and is
likely to have less than nanosecond precision. Each operation in the timer API
will explain how it addresses unit conversion and possible loss of precision.

== Programmer's model

Each task gets a timer. The timer has three properties:

- An _enable bit._
- A _deadline._
- A _notification set._

At periodic intervals (ticks), if the enable bit is set, the kernel checks the
deadline to see if it is in the future. If not (it is `>=` the current time),
the kernel will

- Clear the enable bit.
- Bitwise-OR the notification set into the task's notification bits.

The task will find out about this next time it enters `receive` with the
notification bits unmasked -- or, if the task is blocked in `receive` at the
time the timer fires, immediately.

Because the enable bit is cleared when the timer fires, tasks can assume that
setting their timer will result in exactly zero or one notification events.

If a task sets the timer notification set to `0`, it will not receive a
notification when the timer fires, but it could still poll the enable bit.

By default, when a task is created, its timer is set up as:

- Enable bit clear.
- Deadline `!0` (i.e. the distant future)
- Notification set `0` (i.e. no bits)

== Timer control operations

These will either be syscalls, or messages to the kernel. The fact that every
task has a timer and the timer requires no privilege to use suggests that
syscalls are appropriate; the desire to possibly implement timers in userspace
someday suggests messages.

Either way, the set of operations is expected to be:

=== Read Current Time

Gets the current time, measured in nanoseconds from some point in the past. This
is only useful for relative measurements during the same boot of the system.

Note that the time that is observed is in the past, for two reasons:

1. By the time it is copied up to the task, time has elapsed.

2. The kernel is probably keeping time with less than nanosecond precision.

=== Set Timer

Sets the timer's enable bit and loads a new 64-bit timestamp and notification
set.

=== Clear Timer

Clears the timer's enable bit. Once this operation returns, the timer will not
post new notifications to the task (though if the timer has already expired, the
notification stays posted).

=== Read Timer State

Reads out the enable bit, timestamp, and notification set associated with the
timer.

== Implementation notes

=== ARMv7-M / ARMv8-M

The M-profiles specify a `SysTick` peripheral, which is a 24-bit down-counter
running at the CPU clock frequency that can generate interrupts on overflow.

This timer is nice because it's always present, but it's also quite limited. Its
relatively narrow counter means that it can't be used to schedule interrupts at
arbitrary future times (at 100MHz, it's limited to 16.7ms). Its fast update rate
and use of a down-counter with reload value, rather than up-counter with compare
register, means it's also hard to schedule variable _short_ intervals with it.

The thing that `SysTick` was designed for, and the thing it's good at, is
generating an interrupt with a fixed, regular period. On a *ticked* system, this
interrupt handler is usually charged with

- Updating a tick counter.
- Checking for expired timers.

That is, the time-keeping frequency is set by `SysTick`'s rollover period, *not*
its count frequency, and time must be maintained by an ISR. This has some
drawbacks.

1. You need to take regular interrupts to keep time. An interrupt every 1-10ms
is not unusual.

2. You need to take those interrupts *promptly* or you risk missing ticks and
losing time. A long critical section, or storm of higher-priority interrupts,
can interfere with timekeeping.

In practice, the cost of taking the interrupts is often acceptable, and careful
application of interrupt priorities (and avoiding critical sections!) can keep
timekeeping reliable.

The other option is a *tickless* system. A tickless system can keep time without
taking frequent interrupts. This is usually implemented by using a longer-period
or slower-clocked timer with a compare register, so that interrupts can be
scheduled farther in advance.

Unfortunately, the ARM architecture mandates no such timer, so this makes
timekeeping vendor-specific. Systems usually incur this complexity only in cases
where the decrease in interrupts can significantly extend battery life, e.g.
things running for years off watch batteries.

The current thinking for Hubris is to use `SysTick` to generate a regular tick
with roughly millisecond precision, but simulate nanosecond precision at the
kernel API.

=== RISC-V

TBD
