[#caboose]
= The caboose

At times, users may wish for a Hubris archive to contain information with the
following properties:

* Decided **after** the image is built
* Readable in a wide variety of situations:
** A live system with well-known APIs to request it (e.g. over the network)
** A Hubris build archive
** A binary file, given the original build archive
** A binary file, **without** the original build archive

Note that a live system with a debugger attached is morally equivalent to "a
binary file", because we can read arbitrary memory.

The motivating example of this data is a component-level version: after building
an image, a separate release engineering process wants to assign it a
user-facing version (e.g. `1.2.3`) and store that information _somewhere_ in the
image.

The "caboose" is a region of flash allocated for this purpose. It is declared
with a `[caboose]` section in an `app.toml`, e.g.

[#caboose-words]
```toml
[caboose]
region = "flash"
size = 128
tasks = ["caboose_reader"]
```

If this section is present in an `app.toml`, the build system reserves an
appropriately-aligned section of memory for the caboose.  The caboose is located
at the **end** of flash (after the final task), and is aligned so that it can be
mapped as an MPU region. Only tasks declared in `caboose.tasks` are allowed to
read data from the caboose region of flash.  If other tasks attempt to read from
this memory region, they will experience the typical memory fault.

The Hubris build system will populate the caboose with 32-bit start and end
words, and a sequence of
https://github.com/oxidecomputer/tlvc[TLV-C] key-value pairs containing image
metadata:

[%header,cols="1,1,4"]
|===
| Value
| Type
| Description

| **Start**
| `u32`
| `abi::CABOOSE_MAGIC`

| `GITC` tag
| TLV-C
| The current Git commit hash with an optional trailing "-dirty" if the
repository contains uncommitted changes.

| `BORD` tag
| TLV-C
| The name of the target board, as specified in the image's TOML config.

| `NAME` tag
| TLV-C
| The name of the image, as specified in the image's TOML config.

| `VERS` tag
| TLV-C _(optional)_
| The value of the `HUBRIS_CABOOSE_VERS` environment variable at build time,
if it was set.

| ...
| `u8`
| _(filled with `0xFF`)_

| **End**
| `u32`
| Caboose size (little-endian `u32`)
|===

The caboose's length is included in the `total_image_len` field of
`abi::ImageHeader`.  Because the caboose is located at the end of flash, its
presence and size can be determined as follows:

* Read total image length from the `ImageHeader`
** At runtime, this is a variable that can be read by the kernel
** At rest, the image header is at a known location (depending on
   microcontroller) and includes a distinctive magic number
   (`abi::HEADER_MAGIC`)
* Read the final word of the image, which may be the caboose length
* Subtract this value from total image length to get the (presumptive) caboose
  start
** If this subtraction underflows or exceeds the bounds of flash, the caboose is
   not present.
* Read the first word of the (presumptive) caboose
** If this word is not `abi::CABOOSE_MAGIC`, then the caboose is not present
** Otherwise, the caboose position and length is now known

Note that this procedure works both at runtime and from a binary file, with or
without an associated Hubris archive.

To reduce runtime overhead, the caboose position may also be baked into an
individual task image at build time. This is implemented in the
`drv-caboose-pos` crate:
```rust
let caboose: Option<&'static [u8]> = drv_caboose_pos::CABOOSE_POS.as_slice();
```

(This functionality requires cooperation with the `xtask` build system, as we
can't know the caboose position until all tasks have been built)

Besides the start and end words and the default metadata described above, the
Hubris build system is agnostic to any further contents of the caboose. A
separate release engineering process may decide to store any arbitrary data in
the remaining space. The
https://github.com/oxidecomputer/hubtools[`hubtools` repository] includes a
library and CLI for modifying the caboose of a Hubris archive.
