// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use abi::{ImageHeader, ImageVectors};
use drv_lpc55_flash::{Flash, BYTES_PER_FLASH_PAGE};
use sha3::{Digest, Sha3_256};
use stage0_handoff::{ImageVersion, RotImageDetails};
use unwrap_lite::UnwrapLite;

pub fn get_image_b(flash: &mut Flash<'_>) -> Option<Image> {
    let imageb = unsafe { &__IMAGE_B_BASE };

    let img = Image {
        flash: FLASH_B,
        vector: imageb,
    };

    if img.validate(flash) {
        Some(img)
    } else {
        None
    }
}

pub fn get_image_a(flash: &mut Flash<'_>) -> Option<Image> {
    let imagea = unsafe { &__IMAGE_A_BASE };

    let img = Image {
        flash: FLASH_A,
        vector: imagea,
    };

    if img.validate(flash) {
        Some(img)
    } else {
        None
    }
}

extern "C" {
    static __IMAGE_A_BASE: abi::ImageVectors;
    static __IMAGE_B_BASE: abi::ImageVectors;
    // __vector size is currently defined in the linker script as
    //
    // __vector_size = SIZEOF(.vector_table);
    //
    // which is a symbol whose value is the size of the vector table (i.e.
    // there is no actual space allocated). This is best represented as a zero
    // sized type which gets accessed by addr_of! as below.
    static __vector_size: [u8; 0];
}

// BYTES_PER_FLASH_PAGE is a usize so redefine the constant here to avoid having
// to do the u32 change everywhere
const PAGE_SIZE: u32 = BYTES_PER_FLASH_PAGE as u32;

pub struct Image {
    flash: Range<u32>,
    vector: &'static ImageVectors,
}

pub fn image_details(img: Image, flash: &mut Flash<'_>) -> RotImageDetails {
    RotImageDetails {
        digest: img.get_fwid(flash),
        version: img.get_image_version(),
    }
}

impl Image {
    fn get_img_start(&self) -> u32 {
        self.vector as *const ImageVectors as u32
    }

    fn get_img_size(&self) -> Option<usize> {
        usize::try_from((unsafe { &*self.get_header() }).total_image_len).ok()
    }

    fn get_header(&self) -> *const ImageHeader {
        // SAFETY: This generated by the linker script which we trust
        // Note that this is generated from _this_ image's linker script
        // as opposed to the _image_ linker script but those two _must_
        // be the same value!
        let vector_size = unsafe { core::ptr::addr_of!(__vector_size) as u32 };
        (self.get_img_start() + vector_size) as *const ImageHeader
    }

    /// Make sure all of the image flash is programmed
    fn validate(&self, flash: &mut Flash<'_>) -> bool {
        let img_start = self.get_img_start();

        // Start by making sure we can access the page where the vectors live
        let valid = flash.is_page_range_programmed(img_start, PAGE_SIZE);

        if !valid {
            return false;
        }

        let header_ptr = self.get_header();

        // Next validate the header location is programmed
        let valid =
            flash.is_page_range_programmed(header_ptr as u32, PAGE_SIZE);

        if !valid {
            return false;
        }

        // SAFETY: We've validated the header location is programmed so this
        // will not trigger a fault. This is generated from our build scripts
        // which we trust.
        let header = unsafe { &*header_ptr };

        // Does this look correct?
        if header.magic != abi::HEADER_MAGIC {
            return false;
        }

        let total_len = match header.total_image_len.checked_add(PAGE_SIZE - 1)
        {
            Some(s) => s & !(PAGE_SIZE - 1),
            None => return false,
        };

        // Last step is to make sure the entire range is programmed
        flash.is_page_range_programmed(img_start, total_len)
    }

    pub fn get_fwid(&self, flash: &mut Flash<'_>) -> [u8; 32] {
        let mut hash = Sha3_256::new();

        for start in self.flash.clone().step_by(BYTES_PER_FLASH_PAGE) {
            if flash.is_page_range_programmed(start, PAGE_SIZE) {
                // SAFETY: The addresses used in this unsafe code are all
                // generated by build.rs from data in the build environment.
                // The safety of this code is an extension of our trust in
                // the build.
                let page = unsafe {
                    core::slice::from_raw_parts(
                        start as *const u8,
                        BYTES_PER_FLASH_PAGE,
                    )
                };
                hash.update(page);
            }
        }

        hash.finalize().into()
    }

    pub fn get_image_version(&self) -> ImageVersion {
        // SAFETY: We checked this previously
        let header = unsafe { &*self.get_header() };

        ImageVersion {
            epoch: header.epoch,
            version: header.version,
        }
    }

    fn pointer_range(&self) -> core::ops::Range<*const u8> {
        let img_ptr = self.get_img_start() as *const u8;
        // The MPU requires 32 byte alignment and so the compiler pads the
        // image accordingly. The length field from the image header does not
        // (and should not) account for this padding so we must do that here.
        let img_size = (self.get_img_size().unwrap_lite() + 31) & !31;

        // Safety: this is unsafe because the pointer addition could overflow.
        // If that happens, we'll produce an empty range or crash with a panic.
        // We do not dereference these here pointers.
        img_ptr..unsafe { img_ptr.add(img_size) }
    }

    pub fn contains(&self, address: *const u8) -> bool {
        self.pointer_range().contains(&address)
    }
}

include!(concat!(env!("OUT_DIR"), "/config.rs"));
