name: Hubris Remote Build
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: thumbv6m-none-eabi
          components: rust-src

      - name: Build Kernel
        run: |
          export RUSTC_BOOTSTRAP=1
          cargo build -p kern --target thumbv6m-none-eabi

      - name: Save Binary
        uses: actions/upload-artifact@v4
        with:
          name: hubris-kernel-bin
          path: target/thumbv6m-none-eabi/debug/kern
